# Generated by Django 5.0.4 on 2024-05-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_product_baths_product_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
