# Generated by Django 5.0.4 on 2024-06-13 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0006_customuser_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='plan',
            field=models.ForeignKey(blank=True, default='Free', null=True, on_delete=django.db.models.deletion.SET_NULL, to='real_estate.plan'),
        ),
    ]
