# Generated by Django 5.0.4 on 2024-06-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0008_alter_plan_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Anonymous', max_length=50, null=True)),
                ('subject', models.CharField(blank=True, default='Anonymous', max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(blank=True, default='Anonymous', max_length=400, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
